---
development:
  cloud_name: upload
  api_key: '196893495867949'
  api_secret: 3dQDLGl-LNusAxGter9n6rHX1DM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: upload
  api_key: '196893495867949'
  api_secret: 3dQDLGl-LNusAxGter9n6rHX1DM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: upload
  api_key: '196893495867949'
  api_secret: 3dQDLGl-LNusAxGter9n6rHX1DM
  enhance_image_tag: true
  static_image_support: false
